variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"
  JULIA_NUM_THREADS: '8'

stages:
  - build
  - test
  - post

.root:
  image: "juliagpu/julia:v1.2-cuda"
  only:
    - master
    - tags
    - external
    - pushes
  artifacts:
    when: always
    paths:
      - Manifest.toml
      - .julia/
      - deps/ext.jl
      - deps/build.log
      - src/*.cov
      - src/*/*.cov
      - src/*/*/*.cov

build:
  extends: .root
  stage: build
  script:
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg; Pkg.build(); using OrdinaryDiffEq;"

.test:
  extends: .root
  stage: test
  dependencies:
    - build

test-multithreading:
  extends: .test
  variables:
    GROUP: "Multithreading"
  script:
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg;
                          Pkg.test(; coverage = true);"

test-GPU:
  extends: .test
  variables:
    GROUP: "GPU"
  script:
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia --project -e "using Pkg; Pkg.add(\"CuArrays\");
                          Pkg.test(; coverage = true);"

coverage:
  extends: .root
  stage: post
  dependencies:
    - test-multithreading
    - test-GPU
  script:
    - julia -e "using InteractiveUtils;
                versioninfo()"
    - julia -e 'using Pkg;
                Pkg.add("Coverage")'
    - julia -e 'using Coverage;
                cl, tl = get_summary(process_folder());
                println("(", cl/tl*100, "%) covered");
                Codecov.submit_local(process_folder(), ".")'
  coverage: '/\(\d+.\d+\%\) covered/'