# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
addons:
  apt:
    packages:
      - gfortran
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install gcc;
    fi ;
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --color=yes -e 'Pkg.clone(pwd())'
  - julia --color=yes -e 'Pkg.build("OrdinaryDiffEq")'
  # Manually resolve test requirements:
  - julia --color=yes -e 'map(Pkg.add, keys(Pkg.Reqs.parse(Pkg.dir("OrdinaryDiffEq", "test", "REQUIRE"))))'
script:
  - julia --color=yes -e 'Pkg.test("OrdinaryDiffEq"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia --color=yes -e 'cd(Pkg.dir("OrdinaryDiffEq")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia --color=yes -e 'cd(Pkg.dir("OrdinaryDiffEq")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
